import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// 自動依資料夾產生：章節順序由資料夾前綴數字決定，頁面順序由檔名前綴決定。
const sidebars: SidebarsConfig = {
  book: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
